name: Changelog Release
description: Generate a changelog release file summarising the latest pull requests content
outputs:
    time:
        description: 'The time this action completes'
runs:
    using: 'docker'
    image: 'Dockerfile'
